### ISSUE TITLE
xtext thinks all strings with %s are format strings

### ISSUE THREAD

**Issue by cpeel** [vertilia/text#1]
`xtext` is checking for only the existence of `%` when [detecting php-formatted strings](https://github.com/vertilia/text/blob/main/src/PoDomain.php#L33), but not all strings with `%`s are formatted strings. `xgettext` appears to do some fancy heuristics to guess which is which although it doesn't do a great job. `xgettext` supports a `xgettext:no-php-format` comment above it to indicate that it isn't a format string. When these strings are written out to the file, the `#, php-format` line is not included.

While we could make `xtext` smarter about detecting [PHP-format strings](https://www.php.net/manual/en/function.sprintf.php#refsect1-function.sprintf-parameters) -- a complicated regex would probably get us 99% of the way there -- if `xtext` honored some kind of manual comment that would work just as well.

I'm happy to work up a PR to fix this (or at least to try) but before I went down that path I thought I'd open an issue and see if it's something you're interested in fixing or being fixed.

**Comment by dotgit** [comment]
good point, will add `no-php-format` comment handling
